
# 日志
logger:
  level: debug
  levelColor: true
  format: json
  stdout: true
  file:
    filename: "../logs/task.log"
    maxSize: 500

yjs_task:
  url: "https://www.yingjiesheng.com/hebeijob/list_%s.html"
  code: "YJS"
  retry: 3
  name: "应届生求职网"

