version: '3.4'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    restart: always